# Generated by Django 5.2.9 on 2025-12-09 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='세션 ID (비로그인 사용자 식별용)', max_length=255, unique=True)),
                ('title', models.CharField(default='새 대화', help_text='대화 제목 (첫 메시지에서 자동 생성)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='로그인한 사용자 (비로그인 시 null)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='전공명', max_length=255, unique=True)),
                ('cluster', models.CharField(help_text='계열 (예: 공학계열, 인문계열)', max_length=100)),
                ('summary', models.TextField(help_text='전공 요약 설명')),
                ('interest', models.TextField(help_text='관심사 및 적성')),
                ('property', models.TextField(help_text='전공 특성')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='평균 연봉 (만원)', max_digits=10, null=True)),
                ('employment_rate', models.CharField(blank=True, help_text='취업률', max_length=50, null=True)),
                ('department', models.TextField(help_text='관련 학과명 (쉼표로 구분)')),
                ('relate_subjects', models.JSONField(help_text='관련 과목 정보')),
                ('career_activities', models.JSONField(blank=True, help_text='진로 활동', null=True)),
                ('jobs', models.TextField(help_text='진출 직업 (쉼표로 구분)')),
                ('qualifications', models.TextField(blank=True, help_text='관련 자격증 (쉼표로 구분)', null=True)),
                ('enter_fields', models.JSONField(blank=True, help_text='진출 분야 정보', null=True)),
                ('main_subjects', models.JSONField(blank=True, help_text='주요 과목 정보', null=True)),
                ('chart_data', models.JSONField(blank=True, help_text='통계 데이터 (성별, 분야, 연봉, 만족도 등)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='unigo_app_m_name_b79b43_idx'), models.Index(fields=['cluster'], name='unigo_app_m_cluster_871cb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MajorRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='세션 ID (비로그인 사용자 식별용)', max_length=255)),
                ('onboarding_answers', models.JSONField(help_text='온보딩 질문 답변 (subjects, interests, desired_salary, preferred_majors)')),
                ('recommended_majors', models.JSONField(help_text='추천된 전공 목록 및 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='메시지 역할 (user/assistant/system)', max_length=10)),
                ('content', models.TextField(help_text='메시지 내용')),
                ('metadata', models.JSONField(blank=True, help_text='추가 정보 (tool 호출, 검색 결과 등)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='unigo_app.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='대학명', max_length=255)),
                ('area', models.CharField(help_text='지역', max_length=100)),
                ('campus_name', models.CharField(help_text='캠퍼스명', max_length=255)),
                ('school_url', models.URLField(blank=True, help_text='대학 홈페이지 URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'campus_name'],
                'indexes': [models.Index(fields=['name'], name='unigo_app_u_name_fda694_idx'), models.Index(fields=['area'], name='unigo_app_u_area_29c985_idx')],
                'unique_together': {('name', 'campus_name')},
            },
        ),
        migrations.CreateModel(
            name='MajorUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name_at_university', models.CharField(help_text='해당 대학에서의 전공명 (대학마다 다를 수 있음)', max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='unigo_app.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='unigo_app.university')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='unigo_app_c_user_id_2cdc59_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session_id'], name='unigo_app_c_session_2c75b4_idx'),
        ),
        migrations.AddIndex(
            model_name='majorrecommendation',
            index=models.Index(fields=['user', '-created_at'], name='unigo_app_m_user_id_49f257_idx'),
        ),
        migrations.AddIndex(
            model_name='majorrecommendation',
            index=models.Index(fields=['session_id'], name='unigo_app_m_session_054fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='unigo_app_m_convers_b20267_idx'),
        ),
        migrations.AddIndex(
            model_name='majoruniversity',
            index=models.Index(fields=['major'], name='unigo_app_m_major_i_3af346_idx'),
        ),
        migrations.AddIndex(
            model_name='majoruniversity',
            index=models.Index(fields=['university'], name='unigo_app_m_univers_837754_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='majoruniversity',
            unique_together={('major', 'university')},
        ),
    ]
