# Generated by Django 6.0 on 2025-12-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unigo_app", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="custom_image",
            field=models.ImageField(
                blank=True,
                help_text="사용자가 업로드한 커스텀 캐릭터 이미지",
                null=True,
                upload_to="character_images/",
            ),
        ),
    ]
