# Generated by Django 6.0 on 2025-12-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unigo_app", "0004_userprofile_custom_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="use_custom_image",
            field=models.BooleanField(
                default=False,
                help_text="커스텀 이미지 사용 여부 (캐릭터 선택 시 False, 이미지 업로드 시 True)",
            ),
        ),
    ]
