# Generated by Django 5.2.9 on 2025-12-16 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("unigo_app", "0005_userprofile_use_custom_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="majoruniversity",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="university",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="majoruniversity",
            name="major",
        ),
        migrations.RemoveField(
            model_name="majoruniversity",
            name="university",
        ),
        migrations.DeleteModel(
            name="Major",
        ),
        migrations.DeleteModel(
            name="MajorUniversity",
        ),
        migrations.DeleteModel(
            name="University",
        ),
    ]
