# Generated by Django 5.2.9 on 2025-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unigo_app', '0006_remove_majoruniversity_major_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.CharField(help_text='전공 고유 ID', max_length=255, unique=True)),
                ('major_name', models.CharField(help_text='전공명', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='학과 개요', null=True)),
                ('interest', models.TextField(blank=True, help_text='흥미와 적성', null=True)),
                ('property', models.TextField(blank=True, help_text='학과 특성', null=True)),
                ('job', models.TextField(blank=True, help_text='관련 직업', null=True)),
                ('relate_subject', models.TextField(blank=True, help_text='관련 교과목', null=True)),
                ('enter_field', models.TextField(blank=True, help_text='진출 분야', null=True)),
                ('department_aliases', models.TextField(blank=True, help_text='관련 학과', null=True)),
                ('career_act', models.TextField(blank=True, help_text='진로 탐색 활동', null=True)),
                ('qualifications', models.TextField(blank=True, help_text='관련 자격', null=True)),
                ('main_subject', models.TextField(blank=True, help_text='주요 교과목', null=True)),
                ('university', models.TextField(blank=True, help_text='개설 대학', null=True)),
                ('chart_data', models.TextField(blank=True, help_text='차트 데이터 (JSON)', null=True)),
                ('raw_data', models.TextField(blank=True, help_text='원본 데이터 (JSON)', null=True)),
                ('salary', models.FloatField(blank=True, help_text='평균 연봉 (만원)', null=True)),
                ('employment', models.TextField(blank=True, help_text='취업률 등급', null=True)),
                ('employment_rate', models.FloatField(blank=True, help_text='취업률 (%)', null=True)),
                ('acceptance_rate', models.FloatField(blank=True, help_text='경쟁률', null=True)),
            ],
            options={
                'verbose_name': '전공 (Major)',
                'verbose_name_plural': '전공 목록',
                'db_table': 'majors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='카테고리명 (계열)', max_length=255, unique=True)),
                ('major_names', models.TextField(help_text='포함된 전공 목록 (JSON)')),
            ],
            options={
                'verbose_name': '전공 계열 (Category)',
                'verbose_name_plural': '전공 계열 목록',
                'db_table': 'major_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='대학명', max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='대학 코드', max_length=50, null=True)),
                ('url', models.CharField(blank=True, help_text='홈페이지 URL', max_length=500, null=True)),
            ],
            options={
                'verbose_name': '대학 (University)',
                'verbose_name_plural': '대학 목록',
                'db_table': 'universities',
                'managed': False,
            },
        ),
    ]
